__author__ = 'Irrevocable Cascade'

"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

max = 20
previous = 1
current = [1, 2]
sequence = []
i = 0

while sequence[1] < max:
	sequence.append(sequence[1] + sequence[0])
	sequence.remove(sequence[0])


print(sequence)