__author__ = 'Irrevocable Cascade'

"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

max = 4000000
previous = 1
current = 2
sum = 0
total = 2
even_terms = []

while previous <= max:
	sum = previous + current

	if sum % 2 == 0:
		total += sum

	previous = current
	current = sum

print(total)